// Code generated by go-bindata.
// sources:
// css/index.css
// css/index.css.map
// favicon.ico
// favicons/favicon-120.png
// favicons/favicon-144.png
// favicons/favicon-152.png
// favicons/favicon-180.png
// favicons/favicon-32.png
// js/requirejs/2.1.20/require.min.js
// js/src/build.js
// js/src/index.js
// js/src/lib/jsdefines.js
// js/src/vendor/bootstrap/3.3.5-collapse/bootstrap.min.js
// js/src/vendor/jquery/2.1.4/jquery.min.js
// js/src/vendor/react/0.14.0/react-dom.min.js
// js/src/vendor/react/0.14.0/react-with-addons.min.js
// js/src/vendor/requirejs-domready/2.0.1/domReady.js
// robots.txt
// DO NOT EDIT!

// +build !bin

package assets

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// cssIndexCss reads file data from disk. It returns an error on failure.
func cssIndexCss() (*asset, error) {
	path := filepath.Join(rootDir, "css/index.css")
	name := "css/index.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// cssIndexCssMap reads file data from disk. It returns an error on failure.
func cssIndexCssMap() (*asset, error) {
	path := filepath.Join(rootDir, "css/index.css.map")
	name := "css/index.css.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// faviconIco reads file data from disk. It returns an error on failure.
func faviconIco() (*asset, error) {
	path := filepath.Join(rootDir, "favicon.ico")
	name := "favicon.ico"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// faviconsFavicon120Png reads file data from disk. It returns an error on failure.
func faviconsFavicon120Png() (*asset, error) {
	path := filepath.Join(rootDir, "favicons/favicon-120.png")
	name := "favicons/favicon-120.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// faviconsFavicon144Png reads file data from disk. It returns an error on failure.
func faviconsFavicon144Png() (*asset, error) {
	path := filepath.Join(rootDir, "favicons/favicon-144.png")
	name := "favicons/favicon-144.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// faviconsFavicon152Png reads file data from disk. It returns an error on failure.
func faviconsFavicon152Png() (*asset, error) {
	path := filepath.Join(rootDir, "favicons/favicon-152.png")
	name := "favicons/favicon-152.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// faviconsFavicon180Png reads file data from disk. It returns an error on failure.
func faviconsFavicon180Png() (*asset, error) {
	path := filepath.Join(rootDir, "favicons/favicon-180.png")
	name := "favicons/favicon-180.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// faviconsFavicon32Png reads file data from disk. It returns an error on failure.
func faviconsFavicon32Png() (*asset, error) {
	path := filepath.Join(rootDir, "favicons/favicon-32.png")
	name := "favicons/favicon-32.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsRequirejs2120RequireMinJs reads file data from disk. It returns an error on failure.
func jsRequirejs2120RequireMinJs() (*asset, error) {
	path := filepath.Join(rootDir, "js/requirejs/2.1.20/require.min.js")
	name := "js/requirejs/2.1.20/require.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsSrcBuildJs reads file data from disk. It returns an error on failure.
func jsSrcBuildJs() (*asset, error) {
	path := filepath.Join(rootDir, "js/src/build.js")
	name := "js/src/build.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsSrcIndexJs reads file data from disk. It returns an error on failure.
func jsSrcIndexJs() (*asset, error) {
	path := filepath.Join(rootDir, "js/src/index.js")
	name := "js/src/index.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsSrcLibJsdefinesJs reads file data from disk. It returns an error on failure.
func jsSrcLibJsdefinesJs() (*asset, error) {
	path := filepath.Join(rootDir, "js/src/lib/jsdefines.js")
	name := "js/src/lib/jsdefines.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsSrcVendorBootstrap335CollapseBootstrapMinJs reads file data from disk. It returns an error on failure.
func jsSrcVendorBootstrap335CollapseBootstrapMinJs() (*asset, error) {
	path := filepath.Join(rootDir, "js/src/vendor/bootstrap/3.3.5-collapse/bootstrap.min.js")
	name := "js/src/vendor/bootstrap/3.3.5-collapse/bootstrap.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsSrcVendorJquery214JqueryMinJs reads file data from disk. It returns an error on failure.
func jsSrcVendorJquery214JqueryMinJs() (*asset, error) {
	path := filepath.Join(rootDir, "js/src/vendor/jquery/2.1.4/jquery.min.js")
	name := "js/src/vendor/jquery/2.1.4/jquery.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsSrcVendorReact0140ReactDomMinJs reads file data from disk. It returns an error on failure.
func jsSrcVendorReact0140ReactDomMinJs() (*asset, error) {
	path := filepath.Join(rootDir, "js/src/vendor/react/0.14.0/react-dom.min.js")
	name := "js/src/vendor/react/0.14.0/react-dom.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsSrcVendorReact0140ReactWithAddonsMinJs reads file data from disk. It returns an error on failure.
func jsSrcVendorReact0140ReactWithAddonsMinJs() (*asset, error) {
	path := filepath.Join(rootDir, "js/src/vendor/react/0.14.0/react-with-addons.min.js")
	name := "js/src/vendor/react/0.14.0/react-with-addons.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsSrcVendorRequirejsDomready201DomreadyJs reads file data from disk. It returns an error on failure.
func jsSrcVendorRequirejsDomready201DomreadyJs() (*asset, error) {
	path := filepath.Join(rootDir, "js/src/vendor/requirejs-domready/2.0.1/domReady.js")
	name := "js/src/vendor/requirejs-domready/2.0.1/domReady.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// robotsTxt reads file data from disk. It returns an error on failure.
func robotsTxt() (*asset, error) {
	path := filepath.Join(rootDir, "robots.txt")
	name := "robots.txt"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"css/index.css": cssIndexCss,
	"css/index.css.map": cssIndexCssMap,
	"favicon.ico": faviconIco,
	"favicons/favicon-120.png": faviconsFavicon120Png,
	"favicons/favicon-144.png": faviconsFavicon144Png,
	"favicons/favicon-152.png": faviconsFavicon152Png,
	"favicons/favicon-180.png": faviconsFavicon180Png,
	"favicons/favicon-32.png": faviconsFavicon32Png,
	"js/requirejs/2.1.20/require.min.js": jsRequirejs2120RequireMinJs,
	"js/src/build.js": jsSrcBuildJs,
	"js/src/index.js": jsSrcIndexJs,
	"js/src/lib/jsdefines.js": jsSrcLibJsdefinesJs,
	"js/src/vendor/bootstrap/3.3.5-collapse/bootstrap.min.js": jsSrcVendorBootstrap335CollapseBootstrapMinJs,
	"js/src/vendor/jquery/2.1.4/jquery.min.js": jsSrcVendorJquery214JqueryMinJs,
	"js/src/vendor/react/0.14.0/react-dom.min.js": jsSrcVendorReact0140ReactDomMinJs,
	"js/src/vendor/react/0.14.0/react-with-addons.min.js": jsSrcVendorReact0140ReactWithAddonsMinJs,
	"js/src/vendor/requirejs-domready/2.0.1/domReady.js": jsSrcVendorRequirejsDomready201DomreadyJs,
	"robots.txt": robotsTxt,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"css": &bintree{nil, map[string]*bintree{
		"index.css": &bintree{cssIndexCss, map[string]*bintree{}},
		"index.css.map": &bintree{cssIndexCssMap, map[string]*bintree{}},
	}},
	"favicon.ico": &bintree{faviconIco, map[string]*bintree{}},
	"favicons": &bintree{nil, map[string]*bintree{
		"favicon-120.png": &bintree{faviconsFavicon120Png, map[string]*bintree{}},
		"favicon-144.png": &bintree{faviconsFavicon144Png, map[string]*bintree{}},
		"favicon-152.png": &bintree{faviconsFavicon152Png, map[string]*bintree{}},
		"favicon-180.png": &bintree{faviconsFavicon180Png, map[string]*bintree{}},
		"favicon-32.png": &bintree{faviconsFavicon32Png, map[string]*bintree{}},
	}},
	"js": &bintree{nil, map[string]*bintree{
		"requirejs": &bintree{nil, map[string]*bintree{
			"2.1.20": &bintree{nil, map[string]*bintree{
				"require.min.js": &bintree{jsRequirejs2120RequireMinJs, map[string]*bintree{}},
			}},
		}},
		"src": &bintree{nil, map[string]*bintree{
			"build.js": &bintree{jsSrcBuildJs, map[string]*bintree{}},
			"index.js": &bintree{jsSrcIndexJs, map[string]*bintree{}},
			"lib": &bintree{nil, map[string]*bintree{
				"jsdefines.js": &bintree{jsSrcLibJsdefinesJs, map[string]*bintree{}},
			}},
			"vendor": &bintree{nil, map[string]*bintree{
				"bootstrap": &bintree{nil, map[string]*bintree{
					"3.3.5-collapse": &bintree{nil, map[string]*bintree{
						"bootstrap.min.js": &bintree{jsSrcVendorBootstrap335CollapseBootstrapMinJs, map[string]*bintree{}},
					}},
				}},
				"jquery": &bintree{nil, map[string]*bintree{
					"2.1.4": &bintree{nil, map[string]*bintree{
						"jquery.min.js": &bintree{jsSrcVendorJquery214JqueryMinJs, map[string]*bintree{}},
					}},
				}},
				"react": &bintree{nil, map[string]*bintree{
					"0.14.0": &bintree{nil, map[string]*bintree{
						"react-dom.min.js": &bintree{jsSrcVendorReact0140ReactDomMinJs, map[string]*bintree{}},
						"react-with-addons.min.js": &bintree{jsSrcVendorReact0140ReactWithAddonsMinJs, map[string]*bintree{}},
					}},
				}},
				"requirejs-domready": &bintree{nil, map[string]*bintree{
					"2.0.1": &bintree{nil, map[string]*bintree{
						"domReady.js": &bintree{jsSrcVendorRequirejsDomready201DomreadyJs, map[string]*bintree{}},
					}},
				}},
			}},
		}},
	}},
	"robots.txt": &bintree{robotsTxt, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

